apiVersion: apps/v1

kind: Deployment

metadata:

  name: httpd

  labels:

    app: nginx

spec:

  replicas: 1

  selector:

    matchLabels:

      app: httpd

  template:

    metadata:

      labels:

        app: httpd

    spec:
      volumes:
      - name: test
        
        persistentVolumeClaim:
        
          claimName: test-vpc
        
      containers:

      - name: httpd

        image: httpd

        ports:

        - containerPort: 80
