kind: PersistentVolume
apiVersion: v1
metadata:
        name: test-vp
        labels:
                type: local
spec:
        storageClassName: manual
        capacity:
                storage: 1Gi
        accessModes:
              - ReadWriteMany
        hostPath:
                path: "/home/ubuntu/data"
