kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: test-vpc
        labels:
                type: local
spec:
        storageClassName: manual
        accessModes:
              - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi
